package action

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/hortonworks/cloud-haunter/config"
	"github.com/hortonworks/cloud-haunter/types"
	"github.com/hortonworks/cloud-haunter/utils"
	log "github.com/sirupsen/logrus"
)

// NewJSON returns the json action implementation writing to stdout.
func NewJSON(cfg *config.Config) types.Action {
	return jsonAction{cfg: cfg, out: os.Stdout}
}

type jsonAction struct {
	cfg *config.Config
	// out is where the rendered JSON is written; injectable so tests can capture
	// it in a buffer instead of swapping the os.Stdout global (which would force
	// the test to run non-parallel).
	out io.Writer
}

func (a jsonAction) Execute(op types.OpType, filter []types.FilterType, items []types.CloudItem) error {
	log.Infof("[JSON] Number of items generated by operation %s and filters %s on accounts %s: %d", op.String(), filter, utils.GetCloudAccountNames(a.cfg.CloudProviders), len(items))
	out, _ := json.MarshalIndent(items, "", "  ")
	_, err := fmt.Fprintln(a.out, string(out))
	return err
}
