package action

import (
	"encoding/json"

	"github.com/hortonworks/cloud-haunter/config"
	"github.com/hortonworks/cloud-haunter/types"
	"github.com/hortonworks/cloud-haunter/utils"
	log "github.com/sirupsen/logrus"
)

// NewLog returns the log action implementation.
func NewLog(cfg *config.Config) types.Action {
	return logAction{cfg}
}

type logAction struct {
	cfg *config.Config
}

func (a logAction) Execute(op types.OpType, filter []types.FilterType, items []types.CloudItem) error {
	log.Infof("[LOG] Number of items generated by operation %s and filters %s on accounts %s: %d", op.String(), filter, utils.GetCloudAccountNames(a.cfg.CloudProviders), len(items))
	for _, item := range items {
		out, _ := json.Marshal(item.GetItem())
		log.Infof("[%s] %s", item.GetCloudType(), string(out))
	}
	return nil
}
