package action

import (
	"encoding/json"

	ctx "github.com/hortonworks/cloud-haunter/context"
	"github.com/hortonworks/cloud-haunter/types"
	"github.com/hortonworks/cloud-haunter/utils"
	log "github.com/sirupsen/logrus"
)

func init() {
	ctx.Actions[types.LogAction] = new(logAction)
}

type logAction struct {
}

func (a logAction) Execute(op types.OpType, filter []types.FilterType, items []types.CloudItem) {
	log.Infof("[LOG] Number of items generated by operation %s and filters %s on accounts %s: %d", op.String(), filter, utils.GetCloudAccountNames(), len(items))
	for _, item := range items {
		out, _ := json.Marshal(item.GetItem())
		log.Infof("[%s] %s", item.GetCloudType(), string(out))
	}
}
