version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12.4
    working_directory: /go/src/github.com/hortonworks/cloud-haunter

    # environment:
    #   TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
    #   - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - pkg-cache

      - run:
          name: Analyzing code
          command: make _check

      - run:
          name: Run unit tests
          command: make test

      - run:
          name: "Building binaries"
          command: make _build

      - save_cache:
          key: pkg-cache
          paths:
            - "/go/pkg"

    #   - store_artifacts:
    #       path: /tmp/test-results
    #       destination: raw-test-output

    #   - store_test_results:
    #       path: /tmp/test-results
